name: EO Language Features Compatibility and Support Tests (HSE compiler)

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  retrieve-tests-matrix:
    name: Retrieve the tests matrix 
    runs-on: ubuntu-latest

    outputs:
      tests-matrix: ${{ steps.set-tests-matrix.outputs.matrix }}

    steps:
    - name: Collect tests info and form the matrix to run tests
      id: set-tests-matrix
      run: python3 python/retrieve-tests-matrix.py

  check-matrix:
    name: Check the tests matrix for validity
    runs-on: ubuntu-latest
    needs: retrieve-tests-matrix
    steps:
      - name: Install json2yaml
        run: |
          sudo npm install -g json2yaml

      - name: Check the tests matrix definition
        run: |
          matrix='${{ needs.retrieve-tests-matrix.outputs.tests-matrix }}'
          echo $matrix
          echo $matrix | jq .
          echo $matrix | json2yaml

  run-tests:
    name: ${{ matrix.name }}
    runs-on: ubuntu-latest
    needs: retrieve-tests-matrix

    strategy:
      fail-fast: false
      matrix: ${{ fromJson(needs.retrieve-tests-matrix.outputs.tests-matrix) }}

    steps:
    - uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'

    - name: Cache the local Maven for better performance
      uses: actions/cache@v2
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
                    ${{ runner.os }}-maven-

    - name: Run the "${{ matrix.name }}" test
      run: python3 python/run-test.py ${{ matrix.directory }} hse